pipeline{
    agent{
        label "nodejs"
    }
        environment {
        OPENSHIFT_SERVER = "https://api.eu46r.prod.ole.redhat.com:6443/"
        OPENSHIFT_TOKEN = credentials('Openshift-jenkins-account')
        RHT_OCP4_DEV_USER = 'jenkins'
    }
    stages{
        stage('Deploy') {
            steps {
                sh '''
                    oc login --token=${OPENSHIFT_TOKEN} --server=${OPENSHIFT_SERVER}
                    oc project jenkins
                    oc start-build greeting-service-7 --follow --wait
                '''
            }
        }
    }
}
